from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Users(models.Model):
	username = models.CharField(max_length=20)
	password = models.CharField(max_length=20)
	userid = models.CharField(max_length=30)
	realname = models.CharField(max_length=20)
	idcard = models.CharField(max_length=20)
	phonenumber = models.CharField(max_length=20)
	email = models.EmailField(blank=True)

class Ticketinfo(models.Model):
	trainnumber = models.CharField(max_length=20)
	startstation = models.CharField(max_length=20)
	destination = models.CharField(max_length=20)
	starttime = models.TimeField()
	arrivetime = models.TimeField()
	businessseatprice = models.IntegerField(default=0)
	principalseatprice = models.IntegerField(default=0)
	firstclassseatprice = models.IntegerField(default=0)
	secondclassseatprice = models.IntegerField(default=0)
	advancedsoftseatprice = models.IntegerField(default=0)
	softsleeperprice = models.IntegerField(default=0)
	hardsleeperprice = models.IntegerField(default=0)
	softseatprice = models.IntegerField(default=0)
	hardseatprice = models.IntegerField(default=0)
	noseatprice = models.IntegerField(default=0)
	othersprice = models.IntegerField(default=0)
	businessseattotal = models.IntegerField(default=0)
	principalseattotal = models.IntegerField(default=0)
	firstclassseattotal = models.IntegerField(default=0)
	secondclassseattotal = models.IntegerField(default=0)
	advancedsoftseattotal = models.IntegerField(default=0)
	softsleeperttotal = models.IntegerField(default=0)
	hardsleepertotal = models.IntegerField(default=0)
	softseattotal = models.IntegerField(default=0)
	hardseattotal = models.IntegerField(default=0)
	noseattotal = models.IntegerField(default=0)
	otherstotal = models.IntegerField(default=0)

class Ticketcounts(models.Model):
	trainnumber = models.CharField(max_length=20)
	startdate = models.DateField()
	businessseat = models.IntegerField(default=0)
	principalseat = models.IntegerField(default=0)
	firstclassseat = models.IntegerField(default=0)
	secondclassseat = models.IntegerField(default=0)
	advancedsoftsleeper = models.IntegerField(default=0)
	softsleeper = models.IntegerField(default=0)
	hardsleeper = models.IntegerField(default=0)
	softseat = models.IntegerField(default=0)
	hardseat = models.IntegerField(default=0)
	noseat = models.IntegerField(default=0)
	others = models.IntegerField(default=0)
	businessseatback = models.IntegerField(default=0)
	principalseatback = models.IntegerField(default=0)
	firstclassseatback = models.IntegerField(default=0)
	secondclassseatback = models.IntegerField(default=0)
	advancedsoftsleeper = models.IntegerField(default=0)
	softsleeperback = models.IntegerField(default=0)
	hardsleeperback = models.IntegerField(default=0)
	softseatback = models.IntegerField(default=0)
	hardseatback = models.IntegerField(default=0)
	noseatback = models.IntegerField(default=0)
	othersback = models.IntegerField(default=0)

class Ticketbacks(models.Model):
	trainnumber = models.CharField(max_length=20)
	startdate = models.DateField()
	seattype = models.CharField(max_length=20)
	seatnumber = models.IntegerField(default=0)

class Orders(models.Model):
	ordernumber = models.CharField(max_length=50)
	orderdate = models.DateField()
	userid = models.CharField(max_length=30)
	trainnumber = models.CharField(max_length=20)
	startdate = models.DateField()
	seattype = models.CharField(max_length=20)
	seatnumber = models.IntegerField()
	valid = models.BooleanField(default=True)
