# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainnumber', models.CharField(max_length=20)),
                ('startstation', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('starttime', models.TimeField()),
                ('arrivetime', models.TimeField()),
                ('startdate', models.DateField()),
                ('businessseat', models.IntegerField(blank=True)),
                ('principalseat', models.IntegerField(blank=True)),
                ('firstclassseat', models.IntegerField(blank=True)),
                ('secondclassseat', models.IntegerField(blank=True)),
                ('advancedsoftsleeper', models.IntegerField(blank=True)),
                ('softsleeper', models.IntegerField(blank=True)),
                ('hardsleeper', models.IntegerField(blank=True)),
                ('softseat', models.IntegerField(blank=True)),
                ('hardseat', models.IntegerField(blank=True)),
                ('noseat', models.IntegerField(blank=True)),
                ('others', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('cardid', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
