# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ticket', '0002_auto_20151229_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinfo',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
