# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_ticket', '0003_ticketinfo_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='cardid',
            new_name='idcard',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='realname',
        ),
    ]
