# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ticket', '0006_auto_20160102_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainnumber', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('seattype', models.CharField(max_length=20)),
                ('seatnumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='businessseatback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='firstclassseatback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='hardseatback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='hardsleeperback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='noseatback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='othersback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='principalseatback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='secondclassseatback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='softseatback',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcounts',
            name='softsleeperback',
            field=models.IntegerField(default=0),
        ),
    ]
